//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FS.Monitor.Common.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FS.Monitor.Common.Language.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 A 煤矿 的本地化字符串。
        /// </summary>
        internal static string A_CoalMine {
            get {
                return ResourceManager.GetString("A_CoalMine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常位置 的本地化字符串。
        /// </summary>
        internal static string AbnormalLocation {
            get {
                return ResourceManager.GetString("AbnormalLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BC3异常告警! 的本地化字符串。
        /// </summary>
        internal static string AbnormalWarning {
            get {
                return ResourceManager.GetString("AbnormalWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加速 的本地化字符串。
        /// </summary>
        internal static string Accelerate {
            get {
                return ResourceManager.GetString("Accelerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号 的本地化字符串。
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加设备 的本地化字符串。
        /// </summary>
        internal static string AddDevice {
            get {
                return ResourceManager.GetString("AddDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加项目 的本地化字符串。
        /// </summary>
        internal static string AddItem {
            get {
                return ResourceManager.GetString("AddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报警提醒 的本地化字符串。
        /// </summary>
        internal static string AlarmToRemind {
            get {
                return ResourceManager.GetString("AlarmToRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自主学习 的本地化字符串。
        /// </summary>
        internal static string AutonomyLearning {
            get {
                return ResourceManager.GetString("AutonomyLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自主学习已完成 的本地化字符串。
        /// </summary>
        internal static string AutonomyLearningCompleted {
            get {
                return ResourceManager.GetString("AutonomyLearningCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 B 煤矿 的本地化字符串。
        /// </summary>
        internal static string B_CoalMine {
            get {
                return ResourceManager.GetString("B_CoalMine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在学习中.... 的本地化字符串。
        /// </summary>
        internal static string BeingLearning {
            get {
                return ResourceManager.GetString("BeingLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 皮带损伤等级 的本地化字符串。
        /// </summary>
        internal static string BeltDamageGrade {
            get {
                return ResourceManager.GetString("BeltDamageGrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 皮带位置 的本地化字符串。
        /// </summary>
        internal static string BeltPosition {
            get {
                return ResourceManager.GetString("BeltPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 皮带速度 的本地化字符串。
        /// </summary>
        internal static string BeltSpeed {
            get {
                return ResourceManager.GetString("BeltSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 相机 的本地化字符串。
        /// </summary>
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色度 的本地化字符串。
        /// </summary>
        internal static string Chroma {
            get {
                return ResourceManager.GetString("Chroma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 色度 的本地化字符串。
        /// </summary>
        internal static string Chrominance {
            get {
                return ResourceManager.GetString("Chrominance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清洁罩转速调节 的本地化字符串。
        /// </summary>
        internal static string CleanCoverSpeedAdjustment {
            get {
                return ResourceManager.GetString("CleanCoverSpeedAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关闭 的本地化字符串。
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关 的本地化字符串。
        /// </summary>
        internal static string CloseTag {
            get {
                return ResourceManager.GetString("CloseTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对比度 的本地化字符串。
        /// </summary>
        internal static string Contrast {
            get {
                return ResourceManager.GetString("Contrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 控制箱 的本地化字符串。
        /// </summary>
        internal static string ControlBox {
            get {
                return ResourceManager.GetString("ControlBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输送机选择 的本地化字符串。
        /// </summary>
        internal static string ConveyorChoice {
            get {
                return ResourceManager.GetString("ConveyorChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CPU 温度 的本地化字符串。
        /// </summary>
        internal static string CPUTemperature {
            get {
                return ResourceManager.GetString("CPUTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前选择 的本地化字符串。
        /// </summary>
        internal static string CurrentChoice {
            get {
                return ResourceManager.GetString("CurrentChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前线路1 的本地化字符串。
        /// </summary>
        internal static string CurrentLineOne {
            get {
                return ResourceManager.GetString("CurrentLineOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前监测测点 的本地化字符串。
        /// </summary>
        internal static string CurrentMonitoringPoint {
            get {
                return ResourceManager.GetString("CurrentMonitoringPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 减速 的本地化字符串。
        /// </summary>
        internal static string Decelerate {
            get {
                return ResourceManager.GetString("Decelerate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除当前项目? 的本地化字符串。
        /// </summary>
        internal static string delProject {
            get {
                return ResourceManager.GetString("delProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 部门名称 的本地化字符串。
        /// </summary>
        internal static string DepartmentName {
            get {
                return ResourceManager.GetString("DepartmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除当前设备? 的本地化字符串。
        /// </summary>
        internal static string DetermineDeleteCurrentEquipment {
            get {
                return ResourceManager.GetString("DetermineDeleteCurrentEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备名称 的本地化字符串。
        /// </summary>
        internal static string Device_Name {
            get {
                return ResourceManager.GetString("Device_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备管理 的本地化字符串。
        /// </summary>
        internal static string DeviceManage {
            get {
                return ResourceManager.GetString("DeviceManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备名称： 的本地化字符串。
        /// </summary>
        internal static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备编号: 的本地化字符串。
        /// </summary>
        internal static string DeviceNumber {
            get {
                return ResourceManager.GetString("DeviceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备运行 的本地化字符串。
        /// </summary>
        internal static string DeviceRunning {
            get {
                return ResourceManager.GetString("DeviceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备状态 的本地化字符串。
        /// </summary>
        internal static string DeviceStatus {
            get {
                return ResourceManager.GetString("DeviceStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示坐标 的本地化字符串。
        /// </summary>
        internal static string DisplayCoordinate {
            get {
                return ResourceManager.GetString("DisplayCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 防尘罩转速调节 的本地化字符串。
        /// </summary>
        internal static string DustCoverSpeedAdjustment {
            get {
                return ResourceManager.GetString("DustCoverSpeedAdjustment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 急停 的本地化字符串。
        /// </summary>
        internal static string EmergencyStop {
            get {
                return ResourceManager.GetString("EmergencyStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即启用 的本地化字符串。
        /// </summary>
        internal static string Enable_Now {
            get {
                return ResourceManager.GetString("Enable_Now", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即启用： 的本地化字符串。
        /// </summary>
        internal static string EnableNow {
            get {
                return ResourceManager.GetString("EnableNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束时间 的本地化字符串。
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 异常记录 的本地化字符串。
        /// </summary>
        internal static string ExceptionRecord {
            get {
                return ResourceManager.GetString("ExceptionRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出系统 的本地化字符串。
        /// </summary>
        internal static string ExitSystem {
            get {
                return ResourceManager.GetString("ExitSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选 的本地化字符串。
        /// </summary>
        internal static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向后翻阅 的本地化字符串。
        /// </summary>
        internal static string FlipBack {
            get {
                return ResourceManager.GetString("FlipBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 向前翻阅 的本地化字符串。
        /// </summary>
        internal static string FlipForward {
            get {
                return ResourceManager.GetString("FlipForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显卡温度 的本地化字符串。
        /// </summary>
        internal static string GraphicsCardTemperature {
            get {
                return ResourceManager.GetString("GraphicsCardTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动喷淋 的本地化字符串。
        /// </summary>
        internal static string HandSpray {
            get {
                return ResourceManager.GetString("HandSpray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏坐标 的本地化字符串。
        /// </summary>
        internal static string HideCoordinate {
            get {
                return ResourceManager.GetString("HideCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 历史事件 的本地化字符串。
        /// </summary>
        internal static string HistoricalEvents {
            get {
                return ResourceManager.GetString("HistoricalEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图像操作 的本地化字符串。
        /// </summary>
        internal static string ImageManipulation {
            get {
                return ResourceManager.GetString("ImageManipulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址 的本地化字符串。
        /// </summary>
        internal static string IP_Address {
            get {
                return ResourceManager.GetString("IP_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IP地址: 的本地化字符串。
        /// </summary>
        internal static string IpAddress {
            get {
                return ResourceManager.GetString("IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否启用 的本地化字符串。
        /// </summary>
        internal static string IsNotEnable {
            get {
                return ResourceManager.GetString("IsNotEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自主学习 的本地化字符串。
        /// </summary>
        internal static string Learning {
            get {
                return ResourceManager.GetString("Learning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 灯光亮度 的本地化字符串。
        /// </summary>
        internal static string LightBrightness {
            get {
                return ResourceManager.GetString("LightBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线路1 的本地化字符串。
        /// </summary>
        internal static string Line_1 {
            get {
                return ResourceManager.GetString("Line_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线路编号： 的本地化字符串。
        /// </summary>
        internal static string Line_Number {
            get {
                return ResourceManager.GetString("Line_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线路编号 的本地化字符串。
        /// </summary>
        internal static string LineNumber {
            get {
                return ResourceManager.GetString("LineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 线路选择： 的本地化字符串。
        /// </summary>
        internal static string LineSelect {
            get {
                return ResourceManager.GetString("LineSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纵撕监测管理系统V0.0.1 的本地化字符串。
        /// </summary>
        internal static string LongitudinalMonitorManagementSystem {
            get {
                return ResourceManager.GetString("LongitudinalMonitorManagementSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纵撕监测管理系统 的本地化字符串。
        /// </summary>
        internal static string LongitudinalTearingMonitoring {
            get {
                return ResourceManager.GetString("LongitudinalTearingMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 亮度 的本地化字符串。
        /// </summary>
        internal static string Luminance {
            get {
                return ResourceManager.GetString("Luminance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大镜 的本地化字符串。
        /// </summary>
        internal static string Magnifier {
            get {
                return ResourceManager.GetString("Magnifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标记为旧伤 的本地化字符串。
        /// </summary>
        internal static string MarkOldWound {
            get {
                return ResourceManager.GetString("MarkOldWound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最大化 的本地化字符串。
        /// </summary>
        internal static string Maximize {
            get {
                return ResourceManager.GetString("Maximize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最小化 的本地化字符串。
        /// </summary>
        internal static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改设备 的本地化字符串。
        /// </summary>
        internal static string ModifyDevice {
            get {
                return ResourceManager.GetString("ModifyDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改项目 的本地化字符串。
        /// </summary>
        internal static string ModifyItem {
            get {
                return ResourceManager.GetString("ModifyItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 监测管理 的本地化字符串。
        /// </summary>
        internal static string MonitorManage {
            get {
                return ResourceManager.GetString("MonitorManage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增设备 的本地化字符串。
        /// </summary>
        internal static string NewEquipment {
            get {
                return ResourceManager.GetString("NewEquipment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增项目 的本地化字符串。
        /// </summary>
        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编号 的本地化字符串。
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1号点 的本地化字符串。
        /// </summary>
        internal static string OneSignVertex {
            get {
                return ResourceManager.GetString("OneSignVertex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开 的本地化字符串。
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        internal static string Operate {
            get {
                return ResourceManager.GetString("Operate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所属线路 的本地化字符串。
        /// </summary>
        internal static string OwnedLine {
            get {
                return ResourceManager.GetString("OwnedLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 俯仰角度 的本地化字符串。
        /// </summary>
        internal static string PitchAngle {
            get {
                return ResourceManager.GetString("PitchAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 xxx厂 的本地化字符串。
        /// </summary>
        internal static string Plant {
            get {
                return ResourceManager.GetString("Plant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入设备名称 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterDeviceName {
            get {
                return ResourceManager.GetString("PleaseEnterDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入设备编号 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterDeviceNumber {
            get {
                return ResourceManager.GetString("PleaseEnterDeviceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入IP地址 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterIPAddress {
            get {
                return ResourceManager.GetString("PleaseEnterIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入线路编号 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterLineNumber {
            get {
                return ResourceManager.GetString("PleaseEnterLineNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入端口 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterPort {
            get {
                return ResourceManager.GetString("PleaseEnterPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入项目名称 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterProjectName {
            get {
                return ResourceManager.GetString("PleaseEnterProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户名称 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterUserName {
            get {
                return ResourceManager.GetString("PleaseEnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户密码 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterUserPassword {
            get {
                return ResourceManager.GetString("PleaseEnterUserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请再次输入用户密码 的本地化字符串。
        /// </summary>
        internal static string PleaseEnterUserPasswordAgain {
            get {
                return ResourceManager.GetString("PleaseEnterUserPasswordAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1号点 的本地化字符串。
        /// </summary>
        internal static string PointOne {
            get {
                return ResourceManager.GetString("PointOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 3号点 的本地化字符串。
        /// </summary>
        internal static string PointThere {
            get {
                return ResourceManager.GetString("PointThere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 2号点 的本地化字符串。
        /// </summary>
        internal static string PointTwo {
            get {
                return ResourceManager.GetString("PointTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        internal static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口号： 的本地化字符串。
        /// </summary>
        internal static string PortNumber {
            get {
                return ResourceManager.GetString("PortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按Esc退出放大镜 的本地化字符串。
        /// </summary>
        internal static string PressEsc {
            get {
                return ResourceManager.GetString("PressEsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目名称： 的本地化字符串。
        /// </summary>
        internal static string Project_Name {
            get {
                return ResourceManager.GetString("Project_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 项目名称 的本地化字符串。
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改 的本地化字符串。
        /// </summary>
        internal static string Revise {
            get {
                return ResourceManager.GetString("Revise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 饱和度 的本地化字符串。
        /// </summary>
        internal static string Saturation {
            get {
                return ResourceManager.GetString("Saturation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存设置 的本地化字符串。
        /// </summary>
        internal static string SaveSettings {
            get {
                return ResourceManager.GetString("SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全选 的本地化字符串。
        /// </summary>
        internal static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 序号 的本地化字符串。
        /// </summary>
        internal static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统设置 的本地化字符串。
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轻微破损 的本地化字符串。
        /// </summary>
        internal static string SlightlyDamaged {
            get {
                return ResourceManager.GetString("SlightlyDamaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转速调节 的本地化字符串。
        /// </summary>
        internal static string SpeedRegulation {
            get {
                return ResourceManager.GetString("SpeedRegulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 喷淋冲洗 的本地化字符串。
        /// </summary>
        internal static string SprayWash {
            get {
                return ResourceManager.GetString("SprayWash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始学习 的本地化字符串。
        /// </summary>
        internal static string StartLearning {
            get {
                return ResourceManager.GetString("StartLearning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始时间 的本地化字符串。
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新学习 的本地化字符串。
        /// </summary>
        internal static string StudyAgain {
            get {
                return ResourceManager.GetString("StudyAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统管理员 的本地化字符串。
        /// </summary>
        internal static string SystemAdministrator {
            get {
                return ResourceManager.GetString("SystemAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1天7小时55分36秒 的本地化字符串。
        /// </summary>
        internal static string SystemDate {
            get {
                return ResourceManager.GetString("SystemDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统已运行 的本地化字符串。
        /// </summary>
        internal static string SystemRunning {
            get {
                return ResourceManager.GetString("SystemRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前转速 的本地化字符串。
        /// </summary>
        internal static string TurnSpeed {
            get {
                return ResourceManager.GetString("TurnSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户修改 的本地化字符串。
        /// </summary>
        internal static string UserModify {
            get {
                return ResourceManager.GetString("UserModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名称 的本地化字符串。
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户权限 的本地化字符串。
        /// </summary>
        internal static string UserRight {
            get {
                return ResourceManager.GetString("UserRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频预览 的本地化字符串。
        /// </summary>
        internal static string VideoPreview {
            get {
                return ResourceManager.GetString("VideoPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视图控制 的本地化字符串。
        /// </summary>
        internal static string ViewControl {
            get {
                return ResourceManager.GetString("ViewControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 放大 的本地化字符串。
        /// </summary>
        internal static string ZoomIn {
            get {
                return ResourceManager.GetString("ZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩小 的本地化字符串。
        /// </summary>
        internal static string ZoomOut {
            get {
                return ResourceManager.GetString("ZoomOut", resourceCulture);
            }
        }
    }
}
